DATETIME = 'datetime'
ID_USER = 'id_user'
CONTEXT_EVENT = 'context_event'
COMPONENT = 'component'
EVENT = 'event'
DESCRIPTION = 'description'
ORIGIN = 'origin'
IP_ADDRESS = 'ip_address'

N_EVENTS = 'n_events'
EVENTS = 'events'
FIRST_DATETIME = 'first_datetime'
LAST_DATETIME = 'last_datetime'
DAYS_BTW_FIRST_LAST = 'days_btw_first_last'
ORIGIN_USAGE = 'origin_usage'
MEAN_WEEKS = 'mean_weeks'
VARIANCE_WEEKS = 'variance_weeks'
